
# P1 README

***

## P1 Habitat_Type_Maps

### Participants: Anna Krystalli, Jason Griffiths, Paul Richards

### Summary:

The MMO want to know the spatial distribution of habitats around the UK coastline. They have some information but missing much. They do however have a variety of more widely distributed spatial data on species and environmental parameter. We aim to use these to predict the unknown habitats in regions around the UK coastline. We will use a machine learning species distribution modelling approach (random forest) which will allow us to say how certain we are about the predictions we make about habitat classification. We then want to build a shiny up to visualise and interact with predicted probabilistic maps of habitat type distribution.


#### Working mainly in R

1) **Model: Predict habitat type from data:**
    - Decide on data
    - Collect
    - spatial match & process
    - Fit model -> Random forest
    - Cross validate
    - Predict
 
2) **Probability Mapper**
    - Shiny app
        + Each layer will map spatial distribution of probability of habitat type occurrence (probability to be represented by layer opacity)
        + App will allow multiple layer to be overlayed to visualised

***

## RESOURCES

### INFO

Concise PDF of UK Marine Habitat Types: [ukmarinesac.org.uk](ukmarinesac.org.uk)

JNCC UK SeaMap 2010 (doing something similar to our project) [http://jncc.defra.gov.uk/page-5534] (http://jncc.defra.gov.uk/page-5534)

JNCC Habitat Mapping Products [http://jncc.defra.gov.uk/page-6639] (http://jncc.defra.gov.uk/page-6639)

### DATA

European Directory of Marine Environmental Data (EDMED) 
[http://www.bodc.ac.uk/data/information_and_inventories/edmed/search/] (http://www.bodc.ac.uk/data/information_and_inventories/edmed/search/)


Met Office Rolling 24 hour data set of observed marine weather. 
https://data.gov.uk/dataset/latest-marine-observational-data
(Or via Met Office Data Point http://www.metoffice.gov.uk/datapoint)
Observations from buoys, light vessels and coastal stations around the UK and within UK waters. Observation parameters reported include:
                Present weather (code) 
                Air Temp (degrees C) 
                Dew Pt Temp (degrees C) 
                Sea Temp (degrees C) 
                Humidity (%) 
                Wind Speed (knots) 
                Wind direction (degrees) 
                Visibility (nautical miles) 
                Pressure (hPA) 
                Wave Height (metres) 
                Wave period (seconds)
 

JNCC Habitat and Species Point Records of Surveys from a load of different points around the coast over the last 40 years. Each csv has details of species/habitats – their locations and descriptions
There are almost 500 of these indiviudal csvs
[https://data.gov.uk/data/search?sort=metadata_modified+desc&publisher=joint-nature-conservation-committee&unpublished=false&page=1] (https://data.gov.uk/data/search?sort=metadata_modified+desc&publisher=joint-nature-conservation-committee&unpublished=false&page=1)  

